name: PR Validation

on:
  pull_request:
    branches: [ "main" ]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.10.0'
        cache: 'npm'

    - name: Install Dependencies
      run: npm ci

    - name: Lint Application
      run: npm run lint

    - name: Test Application
      run: npm run test

    - name: Build Application
      run: npm run build

    - name: Audit Dependencies
      run: npm audit --audit-level=moderate
